### ISSUE TITLE
Missing ramblings

### ISSUE THREAD

**Issue by sseg** [coffeemug/defmacro#1]
Hi @coffeemug 

It seems this may have been intentional, but your post about writing a lisp interpreter in haskell is missing (previously served at http://www.defmacro.org/ramblings/lisp-in-haskell.html). Are then any plans to bring back older ramblings?

Thanks!

**Comment by coffeemug** [comment]
Sorry, I screwed that up. Now fixed.

**Comment by sseg** [comment]
Thanks @coffeemug, I really appreciate you keeping these resources available.
