### ISSUE TITLE
Broken Link for Haskell Lisp Interpreter 

### ISSUE THREAD

**Issue by 2016rshah** [coffeemug/defmacro#2]
I really enjoyed reading your post about the Lisp interpreter you wrote in Haskell. However, at the end of the file it includes a link to the source code. This link is broken, is there anywhere I could poke through the Haskell code for that project?
This is where the link points:
`http://www.defmacro.org/ramblings/lisp-in-haskell/blaise_src.zip`

**Comment by jdriordan** [comment]
@2016rshah You'd think an important file like this would be available somewhere on the internet wouldn't you? Long story short it was on archive.org: https://web.archive.org/web/20090928170052/http://www.defmacro.org:80/ramblings/lisp-in-haskell/blaise_src.zip

**Comment by coffeemug** [comment]
Thanks -- I download the file and put it here -- https://github.com/coffeemug/defmacro/blob/master/ramblings/lisp-in-haskell/blaise_src.zip.

**Comment by 2016rshah** [comment]
❤️ ❤️ ❤️
